services:
  data-agent:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    image: persona-forge:latest
    container_name: persona-forge
    ports:
      - "7860:7860"   # Gradio interface
      - "8000:8000"   # FastAPI if needed
      - "11434:11434" # Ollama server
    
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - PYTHONUNBUFFERED=1
    
    command: ["python", "main.py"]


  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
volumes:
  ollama_data:
